name: ci-github-workflows

on:
  push:
    branches:
      - develop
      - main
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
      - ".github/zizmor.yml"
  pull_request:
    branches:
      - develop
      - main
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
      - ".github/zizmor.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  workflow-ci:
    permissions:
      contents: read
      actions: read
    uses: kokoichi206/gh-actions/.github/workflows/workflow-ci.yml@main
